name: bleijerheide
dependencies:
  - python>=3.9.16,<3.11
  - pandas>=2.0.3,<3.0.0
  - jupyter>=1.0.0,<2.0.0
  - matplotlib>=3.7.2,<4.0.0
  - freetype=2.10.4
  - tensorflow=2.10.0
  - pip
  - pip:
     - pyextremes>=2.3.1,<3.0.0